name: TestPyPI
# This workflow will upload a TestPyPI Python Package using Twine on demand (dispatch)

on: [ workflow_dispatch ]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4

      - name: Publish Test Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          path: ./wheelhouse/*.whl
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
